export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';    
export const ALL_PRODUCT_FAILURE = 'ALL_PRODUCT_FAILURE';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';    
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';    
export const LOGIN_FAILURE = 'LOGIN_FAILURE'; 

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';    
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOAD_USER_REQUEST =  'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS =  'LOAD_USER_SUCCESS';    
export const LOAD_USER_FAILURE =  'LOAD_USER_FAILURE';

export const LOGOUT_SUCCESS =  'LOGOUT_SUCCESS';    
export const LOGOUT_FAILURE =  'LOGOUT_FAILURE';

export const UPDATE_PROFILE_REQUEST =  'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS =  'UPDATE_PROFILE_SUCCESS';    
export const UPDATE_PROFILE_RESET =  'UPDATE_PROFILE_RESET';
export const UPDATE_PROFILE_FAILURE =  'UPDATE_PROFILE_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';


