export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';    
export const ALL_PRODUCT_FAILURE = 'ALL_PRODUCT_FAILURE';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';    
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';    
export const LOGIN_FAILURE = 'LOGIN_FAILURE'; 

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';    
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOAD_USER_REQUEST =  'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS =  'LOAD_USER_SUCCESS';    
export const LOAD_USER_FAILURE =  'LOAD_USER_FAILURE';

export const LOGOUT_SUCCESS =  'LOGOUT_SUCCESS';    
export const LOGOUT_FAILURE =  'LOGOUT_FAILURE';

export const UPDATE_PROFILE_REQUEST =  'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS =  'UPDATE_PROFILE_SUCCESS';    
export const UPDATE_PROFILE_RESET =  'UPDATE_PROFILE_RESET';
export const UPDATE_PROFILE_FAILURE =  'UPDATE_PROFILE_FAILURE';

export const UPDATE_PASSWORD_REQUEST =  'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS =  'UPDATE_PASSWORD_SUCCESS';    
export const UPDATE_PASSWORD_RESET =  'UPDATE_PASSWORD_RESET';
export const UPDATE_PASSWORD_FAILURE =  'UPDATE_PASSWORD_FAILURE';

export const FORGET_PASSWORD_REQUEST =  'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS =  'FORGET_PASSWORD_SUCCESS';    
export const FORGET_PASSWORD_FAILURE =  'FORGET_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST =  'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS =  'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE =  'RESET_PASSWORD_FAILURE';

export const  ADD_TO_CART =  'ADD_TO_CART';
export const  REMOVE_ITEM_CART =  'REMOVE_ITEM_CART';

export const  SAVE_SHIPPING_INFO =  'SAVE_SHIPPING_INFO';

export const CREATE_ORDER_REQUEST =  'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS =  'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE =  'CREATE_ORDER_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';


